import report_resource_detail
import spine_generation
import report_return_materail
import report_borrowe_resources
import report_patron_library_history
import report_no_of_material
import report_status_wise_resources
import librarycard